#!/bin/sh
set -e
echo "[pre-commit] cargo fmt --check"
cargo fmt --all -- --check
echo "[pre-commit] cargo clippy -D warnings"
cargo clippy --all-targets -- -D warnings
echo "[pre-commit] cargo test"
cargo test
